"""enhance interview story

Revision ID: a829a16283ff
Revises: 20260417_01
Create Date: 2026-04-19 14:30:01.986668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a829a16283ff'
down_revision: Union[str, None] = '20260417_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_stories', sa.Column('question_text', sa.Text(), nullable=False))
    op.add_column('interview_stories', sa.Column('answer_markdown', sa.Text(), nullable=True))
    op.add_column('interview_stories', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('interview_stories', sa.Column('linked_achievement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_stories', sa.Column('analysis_chat', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_stories', sa.Column('star_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('interview_stories', 'best_for_json')
    op.drop_column('interview_stories', 'source_type')
    op.drop_column('interview_stories', 'source_ref_id')
    op.drop_column('interview_stories', 'story_json')
    op.drop_column('interview_stories', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_stories', sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('interview_stories', sa.Column('story_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('interview_stories', sa.Column('source_ref_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('interview_stories', sa.Column('source_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('interview_stories', sa.Column('best_for_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('interview_stories', 'star_summary')
    op.drop_column('interview_stories', 'analysis_chat')
    op.drop_column('interview_stories', 'linked_achievement_ids')
    op.drop_column('interview_stories', 'status')
    op.drop_column('interview_stories', 'answer_markdown')
    op.drop_column('interview_stories', 'question_text')
    # ### end Alembic commands ###
