"""add personal okr tables

Revision ID: 3291f9d53700
Revises: 20260420_01
Create Date: 2026-04-20 09:17:33.965034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3291f9d53700'
down_revision: Union[str, None] = '20260420_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_objectives',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_core_level', sa.String(length=64), nullable=True),
    sa.Column('linked_dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_objectives_profile_id'), 'personal_objectives', ['profile_id'], unique=False)
    op.create_table('personal_key_results',
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('result_definition', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_context_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['personal_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_key_results_objective_id'), 'personal_key_results', ['objective_id'], unique=False)
    op.alter_column('interview_stories', 'question_text',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('interview_stories', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_column('interview_stories', 'source_type')
    op.drop_column('interview_stories', 'best_for_json')
    op.drop_column('interview_stories', 'source_ref_id')
    op.drop_column('interview_stories', 'story_json')
    op.drop_column('interview_stories', 'title')
    op.create_index(op.f('ix_resume_interview_answers_resume_id'), 'resume_interview_answers', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_interview_answers_story_id'), 'resume_interview_answers', ['story_id'], unique=False)
    op.create_index(op.f('ix_resume_interview_answers_user_id'), 'resume_interview_answers', ['user_id'], unique=False)
    op.create_index(op.f('ix_resume_interview_answers_workspace_id'), 'resume_interview_answers', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'resume_interview_answers', 'interview_stories', ['story_id'], ['id'])
    op.create_foreign_key(None, 'resume_interview_answers', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'resume_interview_answers', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'resume_interview_answers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_interview_answers', type_='foreignkey')
    op.drop_constraint(None, 'resume_interview_answers', type_='foreignkey')
    op.drop_constraint(None, 'resume_interview_answers', type_='foreignkey')
    op.drop_constraint(None, 'resume_interview_answers', type_='foreignkey')
    op.drop_index(op.f('ix_resume_interview_answers_workspace_id'), table_name='resume_interview_answers')
    op.drop_index(op.f('ix_resume_interview_answers_user_id'), table_name='resume_interview_answers')
    op.drop_index(op.f('ix_resume_interview_answers_story_id'), table_name='resume_interview_answers')
    op.drop_index(op.f('ix_resume_interview_answers_resume_id'), table_name='resume_interview_answers')
    op.add_column('interview_stories', sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('interview_stories', sa.Column('story_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_stories', sa.Column('source_ref_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('interview_stories', sa.Column('best_for_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_stories', sa.Column('source_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('interview_stories', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('interview_stories', 'question_text',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_personal_key_results_objective_id'), table_name='personal_key_results')
    op.drop_table('personal_key_results')
    op.drop_index(op.f('ix_personal_objectives_profile_id'), table_name='personal_objectives')
    op.drop_table('personal_objectives')
    # ### end Alembic commands ###
