"""add weekly reviews

Revision ID: 7d8b3c4310c1
Revises: 3291f9d53700
Create Date: 2026-04-20 09:59:15.463948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d8b3c4310c1'
down_revision: Union[str, None] = '3291f9d53700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_review_runs',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('manager_report_markdown', sa.Text(), nullable=False),
    sa.Column('self_reflection_markdown', sa.Text(), nullable=False),
    sa.Column('new_evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_next_actions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_snapshot_id'], ['capability_assessment_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_review_runs_assessment_snapshot_id'), 'weekly_review_runs', ['assessment_snapshot_id'], unique=False)
    op.create_index(op.f('ix_weekly_review_runs_profile_id'), 'weekly_review_runs', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_review_runs_profile_id'), table_name='weekly_review_runs')
    op.drop_index(op.f('ix_weekly_review_runs_assessment_snapshot_id'), table_name='weekly_review_runs')
    op.drop_table('weekly_review_runs')
    # ### end Alembic commands ###
