"""add resume_interview_answers table

Revision ID: bede7a72aee1
Revises: a829a16283ff
Create Date: 2026-04-19 20:14:41.068275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bede7a72aee1'
down_revision: Union[str, None] = 'a829a16283ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_interview_answers',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('answer_markdown', sa.Text(), nullable=True),
    sa.Column('analysis_chat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('linked_achievement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['interview_stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_interview_answers_resume_id'), 'resume_interview_answers', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_interview_answers_story_id'), 'resume_interview_answers', ['story_id'], unique=False)
    op.create_index(op.f('ix_resume_interview_answers_user_id'), 'resume_interview_answers', ['user_id'], unique=False)
    op.create_index(op.f('ix_resume_interview_answers_workspace_id'), 'resume_interview_answers', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_interview_answers_workspace_id'), table_name='resume_interview_answers')
    op.drop_index(op.f('ix_resume_interview_answers_user_id'), table_name='resume_interview_answers')
    op.drop_index(op.f('ix_resume_interview_answers_story_id'), table_name='resume_interview_answers')
    op.drop_index(op.f('ix_resume_interview_answers_resume_id'), table_name='resume_interview_answers')
    op.drop_table('resume_interview_answers')
    # ### end Alembic commands ###
