"""sync resume interview answer fields

Revision ID: da4e1c07ff30
Revises: bede7a72aee1
Create Date: 2026-04-19 22:00:20.833192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da4e1c07ff30'
down_revision: Union[str, None] = 'bede7a72aee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capability_assessment_snapshots_profile_id'), table_name='capability_assessment_snapshots')
    op.drop_table('capability_assessment_snapshots')
    op.alter_column('interview_stories', 'question_text',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('interview_stories', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'ready'::character varying"))
    op.drop_column('interview_stories', 'source_type')
    op.drop_column('interview_stories', 'story_json')
    op.drop_column('interview_stories', 'title')
    op.drop_column('interview_stories', 'source_ref_id')
    op.drop_column('interview_stories', 'best_for_json')
    op.add_column('resume_interview_answers', sa.Column('star_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resume_interview_answers', sa.Column('confidence_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_interview_answers', 'confidence_score')
    op.drop_column('resume_interview_answers', 'star_summary')
    op.add_column('interview_stories', sa.Column('best_for_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('interview_stories', sa.Column('source_ref_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('interview_stories', sa.Column('title', sa.VARCHAR(length=256), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('interview_stories', sa.Column('story_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('interview_stories', sa.Column('source_type', sa.VARCHAR(length=64), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('interview_stories', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'ready'::character varying"))
    op.alter_column('interview_stories', 'question_text',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.create_table('capability_assessment_snapshots',
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_scope', sa.VARCHAR(length=32), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('core_level', sa.VARCHAR(length=32), server_default=sa.text("'未证明'::character varying"), autoincrement=False, nullable=False),
    sa.Column('core_reasoning_markdown', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('dimension_levels_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('evidence_links_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('next_level_gap_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('suggested_actions_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], name=op.f('capability_assessment_snapshots_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('capability_assessment_snapshots_pkey'))
    )
    op.create_index(op.f('ix_capability_assessment_snapshots_profile_id'), 'capability_assessment_snapshots', ['profile_id'], unique=False)
    # ### end Alembic commands ###
